services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: surgivice-backend
    ports:
      - "4000:4000"   # Backend API port
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=surgivice_dev
      - PORT=4000
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - db  # Ensure backend starts after the database is ready
    restart: unless-stopped

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: surgivice_dev
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql  # Persist database files
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql for database setup
    restart: unless-stopped

volumes:
  db-data:
